import type { components } from "./generated";

type Schemas = components["schemas"];

export type { components, operations, paths } from "./generated";

export type AuthUser = Schemas["AuthUserResponse"];
export type SessionResponse = Schemas["SessionResponse"];
export type IndexedRepo = Schemas["IndexedRepoResponse"];
export type IndexResponse = Schemas["IndexedRepoResponse"];
export type ReposResponse = Schemas["ReposResponse"];
export type SourceMatch = Schemas["SourceMatchResponse"];
export type AskResponse = Schemas["AskResponse"];
export type Workspace = Schemas["WorkspaceResponse"];
export type WorkspacesResponse = Schemas["WorkspacesResponse"];
export type WorkspaceInviteItem = Schemas["WorkspaceInviteListItemResponse"];
export type WorkspaceInvitesResponse = Schemas["WorkspaceInvitesResponse"];
export type WorkspaceMember = Schemas["WorkspaceMemberResponse"];
export type WorkspaceMembersResponse = Schemas["WorkspaceMembersResponse"];
export type JiraSite = Schemas["JiraSiteResponse"];
export type JiraConnection = Schemas["JiraConnectionResponse"];
export type GithubConnection = Schemas["GithubConnectionResponse"];
export type GithubRepository = Schemas["GithubRepositoryResponse"];
export type GithubRepositoriesResponse = Schemas["GithubRepositoriesResponse"];
export type BitbucketConnection = Schemas["BitbucketConnectionResponse"];
export type BitbucketRepository = Schemas["BitbucketRepositoryResponse"];
export type BitbucketRepositoriesResponse = Schemas["BitbucketRepositoriesResponse"];
export type GitlabConnection = Schemas["GitlabConnectionResponse"];
export type GitlabProject = Schemas["GitlabProjectResponse"];
export type GitlabProjectsResponse = Schemas["GitlabProjectsResponse"];
export type SlackTeam = Schemas["SlackTeamResponse"];
export type SlackConnection = Schemas["SlackConnectionResponse"];
export type TeamsTeam = Schemas["TeamsTeamResponse"];
export type TeamsConnection = Schemas["TeamsConnectionResponse"];
export type SlackChannel = Schemas["SlackChannelResponse"];
export type SlackChannelsResponse = Schemas["SlackChannelsResponse"];
export type WorkspaceSlackSource = Schemas["WorkspaceSlackSourceResponse"];
export type WorkspaceSlackSourcesResponse = Schemas["WorkspaceSlackSourcesResponse"];
export type WorkspaceSlackTeam = {
    team_id: string;
    team_name: string;
    team_domain?: string | null;
    linked_by_user_id: string;
    linked_at: string;
    updated_at: string;
    user_oauth_connected: boolean;
};
export type WorkspaceSlackTeamsResponse = {
    teams: WorkspaceSlackTeam[];
};
export type LinearConnection = Schemas["LinearConnectionResponse"];
export type LinearSelectableSource = Schemas["LinearSelectableSourceResponse"];
export type LinearSelectableSourcesResponse = Schemas["LinearSelectableSourcesResponse"];
export type WorkspaceLinearSource = Schemas["WorkspaceLinearSourceResponse"];
export type WorkspaceLinearSourcesResponse = Schemas["WorkspaceLinearSourcesResponse"];
export type ConfluenceConnection = Schemas["ConfluenceConnectionResponse"];
export type ConfluenceSpace = Schemas["ConfluenceSpaceResponse"];
export type ConfluenceSpacesResponse = Schemas["ConfluenceSpacesResponse"];
export type WorkspaceConfluenceSource = Schemas["WorkspaceConfluenceSourceResponse"];
export type WorkspaceConfluenceSourcesResponse = Schemas["WorkspaceConfluenceSourcesResponse"];
export type NotionConnection = Schemas["NotionConnectionResponse"];
export type NotionDatabase = Schemas["NotionDatabaseResponse"];
export type NotionDatabasesResponse = Schemas["NotionDatabasesResponse"];
export type WorkspaceNotionSource = Schemas["WorkspaceNotionSourceResponse"];
export type WorkspaceNotionSourcesResponse = Schemas["WorkspaceNotionSourcesResponse"];
export type JiraProject = Schemas["JiraProjectResponse"];
export type JiraProjectsResponse = Schemas["JiraProjectsResponse"];
export type WorkspaceJiraSite = Schemas["WorkspaceJiraSiteResponse"];
export type WorkspaceJiraSiteStatus = Schemas["WorkspaceJiraSiteStatusResponse"];
export type WorkspaceJiraSource = Schemas["WorkspaceJiraSourceResponse"];
export type WorkspaceJiraSourcesResponse = Schemas["WorkspaceJiraSourcesResponse"];
export type HierarchyNode = Schemas["HierarchyNodeResponse"];
export type HierarchyConnection = Schemas["HierarchyConnectionResponse"];
export type HierarchyGraphResponse = Schemas["HierarchyGraphResponse"];
export type CreateHierarchyNodeResponse = Schemas["CreateHierarchyNodeResponse"];
export type HierarchyAssignableUser = Schemas["HierarchyAssignableUserResponse"];
