from __future__ import annotations

import os
from pathlib import Path

# Project-level paths. Everything generated by the app goes under `.readbase/`
# so the cloned repos and JSON indexes stay separate from source code.
BASE_DIR = Path(__file__).resolve().parents[3]


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def configured_data_dir() -> Path:
    raw_path = os.getenv("READBASE_DATA_DIR")
    if not raw_path:
        return BASE_DIR / ".readbase"
    path = Path(raw_path).expanduser()
    return path if path.is_absolute() else BASE_DIR / path


load_env_file(BASE_DIR / ".env")

DATA_DIR = configured_data_dir()
REPOS_DIR = DATA_DIR / "repos"
INDEX_DIR = DATA_DIR / "indexes"
CHROMA_DIR = DATA_DIR / "chroma"
EMBEDDING_CACHE_DIR = DATA_DIR / "chroma-models"
WORKSPACES_DIR = DATA_DIR / "workspaces"
WORKSPACES_MANIFEST = DATA_DIR / "workspaces.json"
CLI_STATE_FILE = DATA_DIR / "cli-state.json"
DATABASE_URL = os.getenv("DATABASE_URL") or f"sqlite:///{DATA_DIR / 'readbase.db'}"

# Storage routing: saas (default) or customer-owned storage root.
# READBASE_ORG_STORAGE_ROOT is required when READBASE_DEPLOYMENT_MODE=customer.
# READBASE_SCRATCH_DIR defaults to /tmp/readbase-scratch for ephemeral git work.
READBASE_DEPLOYMENT_MODE = os.getenv("READBASE_DEPLOYMENT_MODE", "saas").strip().lower()
READBASE_ORG_STORAGE_ROOT = os.getenv("READBASE_ORG_STORAGE_ROOT", "").strip()
READBASE_SCRATCH_DIR = os.getenv("READBASE_SCRATCH_DIR", "").strip()

# Chunking controls. A "chunk" is the small code/documentation slice we send
# into retrieval and optionally to Claude. Overlap keeps context across chunk
# boundaries so a function split near a boundary still has surrounding lines.
CHUNK_LINES = 120
CHUNK_OVERLAP = 20
MAX_FILE_BYTES = 500_000
DEFAULT_TOP_K = 8

# Folders we skip while walking a repository. These are usually generated,
# dependency-heavy, or unrelated to answering questions about handwritten code.
SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".next",
    ".nuxt",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "target",
    "vendor",
    ".idea",
    ".vscode",
}

# File extensions treated as readable text/code. Binary assets, images, lock
# files that are too large, and compiled outputs should not become RAG context.
TEXT_EXTENSIONS = {
    ".c",
    ".cc",
    ".cfg",
    ".clj",
    ".cpp",
    ".cs",
    ".css",
    ".dart",
    ".Dockerfile",
    ".ex",
    ".exs",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".ini",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".kt",
    ".kts",
    ".lua",
    ".md",
    ".mdx",
    ".php",
    ".proto",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".scss",
    ".sh",
    ".sql",
    ".svelte",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".vue",
    ".xml",
    ".yaml",
    ".yml",
}

# Important text files often have no extension, so they are whitelisted by name.
TEXT_FILENAMES = {
    ".gitignore",
    "Dockerfile",
    "Makefile",
    "README",
    "LICENSE",
}
