export type MessageRole = "user" | "assistant";

export interface ChatMessage {
  id: string;
  role: MessageRole;
  text: string;
  sources?: import("./api/contract").SourceMatch[];
  mode?: string;
}

export type {
  AskResponse,
  AuthUser,
  BitbucketConnection,
  BitbucketRepositoriesResponse,
  BitbucketRepository,
  ConfluenceConnection,
  ConfluenceSpace,
  ConfluenceSpacesResponse,
  CreateHierarchyNodeResponse,
  GithubConnection,
  GithubRepositoriesResponse,
  GithubRepository,
  GitlabConnection,
  GitlabProject,
  GitlabProjectsResponse,
  HierarchyAssignableUser,
  HierarchyConnection,
  HierarchyGraphResponse,
  HierarchyNode,
  IndexResponse,
  IndexedRepo,
  JiraConnection,
  JiraProject,
  JiraProjectsResponse,
  JiraSite,
  LinearConnection,
  LinearSelectableSource,
  LinearSelectableSourcesResponse,
  NotionConnection,
  NotionDatabase,
  NotionDatabasesResponse,
  ReposResponse,
  SessionResponse,
  SlackChannel,
  SlackChannelsResponse,
  SlackConnection,
  SlackTeam,
  SourceMatch,
  TeamsConnection,
  TeamsTeam,
  Workspace,
  WorkspaceConfluenceSource,
  WorkspaceConfluenceSourcesResponse,
  WorkspaceInviteItem,
  WorkspaceInvitesResponse,
  WorkspaceJiraSite,
  WorkspaceJiraSiteStatus,
  WorkspaceJiraSource,
  WorkspaceJiraSourcesResponse,
  WorkspaceLinearSource,
  WorkspaceLinearSourcesResponse,
  WorkspaceMember,
  WorkspaceMembersResponse,
  WorkspaceNotionSource,
  WorkspaceNotionSourcesResponse,
  WorkspaceSlackSource,
  WorkspaceSlackSourcesResponse,
  WorkspaceSlackTeam,
  WorkspaceSlackTeamsResponse,
  WorkspacesResponse,
} from "./api/contract";
