from pathlib import Path

# Project-level paths. Everything generated by the app goes under `.readbase/`
# so the cloned repos and JSON indexes stay separate from source code.
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / ".readbase"
REPOS_DIR = DATA_DIR / "repos"
INDEX_DIR = DATA_DIR / "indexes"
CHROMA_DIR = DATA_DIR / "chroma"
EMBEDDING_CACHE_DIR = DATA_DIR / "chroma-models"

# Chunking controls. A "chunk" is the small code/documentation slice we send
# into retrieval and optionally to Claude. Overlap keeps context across chunk
# boundaries so a function split near a boundary still has surrounding lines.
CHUNK_LINES = 120
CHUNK_OVERLAP = 20
MAX_FILE_BYTES = 500_000
DEFAULT_TOP_K = 8

# Folders we skip while walking a repository. These are usually generated,
# dependency-heavy, or unrelated to answering questions about handwritten code.
SKIP_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "venv",
    "env",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".next",
    ".nuxt",
    "node_modules",
    "dist",
    "build",
    "coverage",
    "target",
    "vendor",
    ".idea",
    ".vscode",
}

# File extensions treated as readable text/code. Binary assets, images, lock
# files that are too large, and compiled outputs should not become RAG context.
TEXT_EXTENSIONS = {
    ".c",
    ".cc",
    ".cfg",
    ".clj",
    ".cpp",
    ".cs",
    ".css",
    ".dart",
    ".Dockerfile",
    ".ex",
    ".exs",
    ".go",
    ".h",
    ".hpp",
    ".html",
    ".ini",
    ".java",
    ".js",
    ".json",
    ".jsx",
    ".kt",
    ".kts",
    ".lua",
    ".md",
    ".mdx",
    ".php",
    ".proto",
    ".py",
    ".rb",
    ".rs",
    ".scala",
    ".scss",
    ".sh",
    ".sql",
    ".svelte",
    ".swift",
    ".toml",
    ".ts",
    ".tsx",
    ".txt",
    ".vue",
    ".xml",
    ".yaml",
    ".yml",
}

# Important text files often have no extension, so they are whitelisted by name.
TEXT_FILENAMES = {
    ".gitignore",
    "Dockerfile",
    "Makefile",
    "README",
    "LICENSE",
}
